---
- import_tasks: pacman.yml
- import_tasks: user.yml
- import_tasks: virtualization.yml
- import_tasks: git.yml
- import_tasks: java.yml
- import_tasks: python.yml
- import_tasks: vim.yml
- import_tasks: i3.yml
- import_tasks: wallpaper.yml

- name: install utilities
  pacman: name={{ item }} state=present
  with_items:
    - alsa-utils
    - aria2
    - curl
    - htop
    - httpie
    - nmap
    - ntp
    - openssh
    - rsync
    - the_silver_searcher
    - nftables
  become: yes

- name: enable network time
  service: name=ntpd state=started enabled=yes
  become: yes

- name: enable firewall
  service: name=nftables state=started enabled=yes
  become: yes

- name: install shell colorschemes
  git: repo=https://github.com/chriskempson/base16-shell.git dest=/home/{{ archlinux_username }}/.config/base16-shell
  become: yes
  become_user: "{{ archlinux_username }}"

- name: install fonts
  pacman: name={{ item }} state=present
  with_items:
    - ttf-dejavu
    - ttf-liberation
    - ttf-droid
    - ttf-inconsolata
    - adobe-source-code-pro-fonts
  become: yes

- name: install GUI
  pacman: name={{ item }} state=present
  with_items:
    - lightdm
    - lightdm-gtk-greeter
    - lxappearance
    - arandr
    - elementary-icon-theme
    - xcursor-simpleandsoft
  become: yes

- name: enable GUI on boot
  service: name=lightdm enabled=yes
  become: yes

- name: template .bashrc
  become: yes
  copy: src=bashrc dest=/home/{{ archlinux_username}}/.bashrc owner={{ archlinux_username }} group=users

- name: template Xresources
  copy: src=Xresources dest=/home/{{ archlinux_username }}/.Xresources owner={{ archlinux_username }} group=users
  become: yes

- name: install pulseaudio/alsa
  pacman: name={{ item }} state=present
  with_items:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - paprefs
    - pavucontrol

- name: install applications
  pacman: name={{ item }} state=present
  with_items:
    - evince
    - firefox
    - gimp
    - krita
    - pcmanfm
    - viewnior
    - vlc
    - xterm
  become: yes

- name: create AUR build directory
  file: name=/home/{{ archlinux_username }}/build state=directory owner={{ archlinux_username }} group=users
  become: yes

- name: create scripts directory
  file: name=/home/{{ archlinux_username }}/bin state=directory owner={{ archlinux_username }} group=users
  become: yes

- name: install utility scripts
  copy: src={{ item }} dest=/home/{{ archlinux_username }}/bin/{{ item }} owner={{ archlinux_username }} group=users mode=755
  with_items:
    - opw
  become: yes
